### ISSUE TITLE
User Stories Template

### ISSUE THREAD

**Issue by P1SMT** [P1SMT/ci-hackathon1-safeguarding#1]
Neeru to create for our Hackathon team

**Comment by NeeruRathour** [comment]
As a user, I want to safeguard information available simply and attractively.

**Comment by NeeruRathour** [comment]
As a user, I want to know my rights so that I can take action accordingly.

**Comment by NeeruRathour** [comment]
As a user, I want to know what actions I can take immediately to safeguard the person.

**Comment by NeeruRathour** [comment]
As a user, I want a visual display(video) of safeguarding in action so that can be easy to understand.

**Comment by NeeruRathour** [comment]
As a user, I want to know the authority or person to be contacted so that quick action can be taken.

**Comment by NeeruRathour** [comment]
As a website owner, I want a home page so that all the services provided by us can be displayed.

**Comment by NeeruRathour** [comment]
As a website owner, I want a safeguarding video on the main page as explaining what safeguarding is.

**Comment by NeeruRathour** [comment]
As a website owner, I want a child safeguarding video on the child page to explain how to safe guard children.

**Comment by NeeruRathour** [comment]
As a website owner, I want an adult safeguarding video on the adult safeguarding page to explain how to safe guard adults.

**Comment by NeeruRathour** [comment]
As a website owner, I want a nav bar with all the links to the important pages.

**Comment by NeeruRathour** [comment]
As a website owner, I want measures to protect page so that can decide what action needs to be taken.

**Comment by NeeruRathour** [comment]
As a website owner, I want to know what all resources are available.

**Comment by NeeruRathour** [comment]
As a website owner, I want Contact Us page so that contact us information can be displayed.

**Comment by NeeruRathour** [comment]
As a website owner, I want social media links in the footer, so that links are on all pages.

**Comment by NeeruRathour** [comment]
As a website owner, I want center section of the page showing content with video.

**Comment by dacnomana** [comment]
Uploading the updated version of the User Stories document:

[S.ON Guardians_User Stories.docx](https://github.com/user-attachments/files/15623484/S.ON.Guardians_User.Stories.docx)
